### ISSUE TITLE
Compatibility with nodebb 8.1

### ISSUE THREAD

**Issue by NormandoHall** [bdharrington7/nodebb-plugin-imgbed#5]
Dear friend. THis plugin is superb and I missing this in 8.1.

Can you update to using in nodeBB 8.1?

Thank you so much

Regards

**Comment by bdharrington7** [comment]
Hi Normando, thanks for the kind words. I'll take a look at what's going on with the compatibility of this plugin later this week or weekend.

Cheers,

-Brian

**Comment by NormandoHall** [comment]
:+1:

**Comment by bdharrington7** [comment]
Hi @NormandoHall I've published an update that allows NodeBB package manager to see the plugin again :beers:

**Comment by NormandoHall** [comment]
Thank you @bdharrington7 , run like a charm. But there is no option for save images in local server like the previous versione of this plugin? I teste with an url image and parses ok, but when I click over, the image pops up with the original source url.

I remember are saved under public/plugins/imgbed.

Regards!

**Comment by bdharrington7** [comment]
Oh you must have been using a really old version of that plugin, I couldn't get it to work correctly so I scrapped it and also baris made a plugin specifically for image upload to imgur. Maybe that will accomplish what you want? See the original post here: 
https://community.nodebb.org/topic/475/nodebb-plugin-imgbed-image-embedding-with-only-a-url
-Brian
