### ISSUE TITLE
Doesn't work on images with variables in the url

### ISSUE THREAD

**Issue by spacedotworks** [bdharrington7/nodebb-plugin-imgbed#6]
Images from Facebook which require the variables after the file extension do not get embedded.

Consider appending `(\\?[a-zA-Z0-9\\&\\=]*)?)` to the regex string for fix.

**Comment by bdharrington7** [comment]
Hi @spacedotworks Thanks for bringing that up, I haven't forgotten about it, just haven't carved out the time to implement and test.

**Comment by spacedotworks** [comment]
i've been using the above regex and it seems to work. had to add a few other characters such as underscore and what not.

**Comment by bdharrington7** [comment]
@spacedotworks do you have examples? I can only find urls like this 1 of every 10 pictures I check. If you've only seen underscores aside from the character set you have above I can add that too
