### ISSUE TITLE
Update 0.2.2 Breaks the Plugin

### ISSUE THREAD

**Issue by scottalanmiller** [bdharrington7/nodebb-plugin-imgbed#7]
0.2.1 was working pretty much perfectly for us.  We updated to 0.2.2 today and all image embedding stopped working.

http://mangolassi.it/topic/7618/images-not-displaying-only-seeing-links

**Comment by bdharrington7** [comment]
Hi @scottalanmiller I'm sorry to hear that, I just went through the thread. That's a very strange thing to happen since I didn't make any major changes to the plugin, I only added tests, and some formatting changes, which added some dev dependencies. 

Did you have any errors in your log?

**Comment by bdharrington7** [comment]
I did test on my own forum and it works so I'm not sure why it stopped working for you... The only thing the might have happened is the 'npm install' didn't happen

**Comment by bdharrington7** [comment]
As for your last comment on the thread, yes, turning off the plugin will leave the image urls as links, as they're parsed on the fly and not actually changed in the source

**Comment by bdharrington7** [comment]
Cannot reproduce
